[project]
name = "ajenticai"
version = "0.1.0"
description = "Agentic AI Project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv",
    "google-genai",
    "groq",
    "ipykernel",
    "langchain",
    "langchain-community",
    "langchain-google-genai",
    "langchain-groq",
    "langchain-mistralai",
    "langchain-tavily",
    "matplotlib",
    "mistralai",
    "numpy",
    "pandas",
    "scikit-learn",
    "streamlit",
    "tiktoken",
    "transformers",
]
